name: Validate

on:
    push:
        branches: ['main']
    pull_request:
        branches-ignore: ['dependabot/**']
    workflow_dispatch:
    schedule:
        # schedule weekly tests, since some dependencies are not intended to be pinned
        # this means: at 23:42 on Fridays
        - cron: '42 23 * * 5'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    OPEN_API_GENERATOR_VERSION: 'v7.16.0'
    PYTHON_VERSION_DEFAULT: '3.12'
    POETRY_VERSION: '2.2.1'

jobs:
    generate-library-code:
        name: Generate Library Code ${{ matrix.language }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                language: ['go', 'java-webclient', 'python', 'typescript']
        steps:
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Create Output Directory
              run: mkdir out/${{ matrix.language }}

            - name: Run OpenAPI Generator
              uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185 # v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PAT }}
                  image: openapitools/openapi-generator-cli:${{ env.OPEN_API_GENERATOR_VERSION }}
                  options: -v ${{ github.workspace }}:/local
                  run: /usr/local/bin/docker-entrypoint.sh batch --clean /local/${{ matrix.language }}.yaml

            - name: Copy LICENSE and our scripts across too
              run: cp LICENSE *.sh ./out/${{ matrix.language }}

            - name: Save to Cache
              uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
              with:
                  path: out/${{ matrix.language }}
                  key: '${{ matrix.language }}-${{ github.run_id }}'

    validate-go:
        name: Validate Go Library
        runs-on: ubuntu-latest
        needs: generate-library-code

        steps:
            - name: Setup Go
              uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c #v6.4.0
              with:
                  go-version: 1.22

            - name: Get generated code from cache
              uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
              with:
                  path: out/go
                  key: 'go-${{ github.run_id }}'
                  fail-on-cache-miss: true

            - name: Build Go API Client
              run: go build -v ./
              working-directory: out/go

            - name: Install test dependencies & run generated tests
              run: |
                  go get github.com/stretchr/testify/assert
                  go test -v ./test/
              working-directory: out/go

    validate-python:
      name: Validate Python Library
      runs-on: ubuntu-latest
      needs: generate-library-code

      steps:
        - name: Set up Python
          uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
          with:
            python-version: ${{ env.PYTHON_VERSION_DEFAULT }}

        - name: Install poetry
          uses: Gr1N/setup-poetry@48b0f77c8c1b1b19cb962f0f00dff7b4be8f81ec # v9
          with:
            poetry-version: ${{ env.POETRY_VERSION }}

        - name: Get generated code from cache
          uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
          with:
            path: out/python
            key: 'python-${{ github.run_id }}'
            fail-on-cache-miss: true

        - name: Install dependencies
          run: poetry install --no-root
          working-directory: out/python

        - name: Ensure build successful
          run: poetry build
          working-directory: out/python

        - name: Run Tests
          run: |
            pip install -r test-requirements.txt
            poetry run pytest
          working-directory: out/python

    validate-java-webclient:
        name: Validate Java Webclient
        runs-on: ubuntu-latest
        needs: generate-library-code

        steps:
            - name: Set up JDK 17 for x64
              uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
              with:
                java-version: '17'
                distribution: 'temurin'
                architecture: x64

            - name: Set up Maven
              uses: stCarolas/setup-maven@12eb41b233df95d49b0c11fc1b5bc8312e5d4ce0 # v5.1
              with:
                maven-version: 3.9.4

            - name: Get generated code from cache
              uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
              with:
                  path: out/java-webclient
                  key: 'java-webclient-${{ github.run_id }}'
                  fail-on-cache-miss: true

            - name: Build & Test Java Webclient API Client
              run: |
                ./update-pom.sh pom.xml
                mvn clean test
              working-directory: out/java-webclient

    validate-typescript:
        name: Validate Typescript Library
        runs-on: ubuntu-latest
        needs: generate-library-code

        steps:
            - name: Setup Node
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e #v6.4.0
              with:
                  node-version: latest

            - name: Get generated code from cache
              uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
              with:
                  path: out/typescript
                  key: 'typescript-${{ github.run_id }}'
                  fail-on-cache-miss: true

            - name: Build Typescript API Client
              run: npm i && npm run build
              working-directory: out/typescript